from typing import TypedDict

class IndicatorDef(TypedDict):
    id: str
    series_id: str
    name_en: str
    name_zh: str
    desc_en: str
    desc_zh: str
    unit: str
    unit_zh: str
    frequency: str
    frequency_zh: str
    category: str
    importance: str  # high / medium
    format: str      # percent / index / thousands / billions / bps / ratio

CATEGORIES = {
    "inflation":     {"en": "Inflation",     "zh": "通膨"},
    "employment":    {"en": "Employment",    "zh": "就業"},
    "growth":        {"en": "Growth",        "zh": "成長"},
    "housing":       {"en": "Housing",       "zh": "房市"},
    "manufacturing": {"en": "Manufacturing", "zh": "製造業"},
    "financial":     {"en": "Financial Markets", "zh": "金融市場"},
    "trade":         {"en": "Trade & Global", "zh": "貿易與國際"},
}

INDICATORS: list[IndicatorDef] = [
    # ── 通膨 ──────────────────────────────────────────────────────────────
    {
        "id": "cpi",
        "series_id": "CPIAUCSL",
        "name_en": "CPI (All Urban)",
        "name_zh": "消費者物價指數 CPI",
        "desc_en": "Measures the change in prices paid by urban consumers for a basket of goods and services. The year-over-year change is the most-watched inflation metric in the US. Above 2% signals elevated inflation; the Fed targets 2% over time.",
        "desc_zh": "衡量城市消費者購買商品和服務的價格變化。年增率是美國最受關注的通膨指標。超過 2% 代表通膨偏高，聯準會的長期通膨目標為 2%。",
        "unit": "Index (1982-84=100)",
        "unit_zh": "指數（1982-84=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "inflation",
        "importance": "high",
        "format": "index",
    },
    {
        "id": "core_cpi",
        "series_id": "CPILFESL",
        "name_en": "Core CPI (ex Food & Energy)",
        "name_zh": "核心 CPI（不含食品與能源）",
        "desc_en": "CPI excluding volatile food and energy prices. Core CPI is the Fed's preferred short-term inflation gauge because it filters out supply-shock noise. Persistently high core CPI is a strong signal for rate hikes.",
        "desc_zh": "剔除波動較大的食品和能源的 CPI。核心 CPI 是聯準會偏好的短期通膨指標，因為它過濾了供給衝擊的噪音。核心 CPI 持續偏高是升息的強烈訊號。",
        "unit": "Index (1982-84=100)",
        "unit_zh": "指數（1982-84=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "inflation",
        "importance": "high",
        "format": "index",
    },
    {
        "id": "core_pce",
        "series_id": "PCEPILFE",
        "name_en": "Core PCE Price Index",
        "name_zh": "核心 PCE 物價指數",
        "desc_en": "The Fed's officially preferred inflation measure. PCE covers a broader range of spending than CPI and adjusts for substitution effects. The FOMC explicitly targets 2% Core PCE as its long-run goal.",
        "desc_zh": "聯準會官方偏好的通膨衡量指標。PCE 涵蓋比 CPI 更廣泛的消費支出，且會調整替代效應。聯邦公開市場委員會明確以 2% 核心 PCE 為長期目標。",
        "unit": "Index (2017=100)",
        "unit_zh": "指數（2017=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "inflation",
        "importance": "high",
        "format": "index",
    },
    {
        "id": "ppi",
        "series_id": "PPIACO",
        "name_en": "PPI (All Commodities)",
        "name_zh": "生產者物價指數 PPI",
        "desc_en": "Measures average change in prices received by domestic producers. PPI is a leading indicator for CPI—rising producer costs often get passed on to consumers. A surge in PPI often precedes consumer inflation by 1-3 months.",
        "desc_zh": "衡量國內生產者收到的價格平均變化。PPI 是 CPI 的領先指標，生產成本上升往往會轉嫁給消費者，PPI 飆升通常比消費通膨早 1-3 個月出現。",
        "unit": "Index (1982=100)",
        "unit_zh": "指數（1982=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "inflation",
        "importance": "medium",
        "format": "index",
    },
    {
        "id": "michigan_inflation",
        "series_id": "MICH",
        "name_en": "UMich Inflation Expectations (1Y)",
        "name_zh": "密大消費者通膨預期（一年期）",
        "desc_en": "University of Michigan survey measuring consumer expectations for inflation over the next year. Anchored inflation expectations are critical for central bank credibility. A jump above 4% raises concern about a wage-price spiral.",
        "desc_zh": "密西根大學調查消費者對未來一年通膨的預期。通膨預期是否穩定對央行公信力至關重要，若飆破 4% 將引發工資-物價螺旋上升的疑慮。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "inflation",
        "importance": "medium",
        "format": "percent",
    },

    # ── 就業 ──────────────────────────────────────────────────────────────
    {
        "id": "nfp",
        "series_id": "PAYEMS",
        "name_en": "Nonfarm Payrolls (NFP)",
        "name_zh": "非農就業人數 NFP",
        "desc_en": "Number of jobs added to the economy (ex-farm & household). The most market-moving monthly release. Above +150K is generally healthy; below +100K signals slowdown. The Fed watches NFP closely alongside inflation.",
        "desc_zh": "美國經濟新增的非農就業人數，是每月最撼動市場的數據。超過 +15 萬通常為健康；低於 +10 萬則暗示放緩，聯準會高度關注此數據。",
        "unit": "Thousands of Persons",
        "unit_zh": "千人",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "high",
        "format": "thousands",
    },
    {
        "id": "unemployment",
        "series_id": "UNRATE",
        "name_en": "Unemployment Rate",
        "name_zh": "失業率",
        "desc_en": "Percentage of the labor force that is unemployed and actively seeking work. At 3.5-4%, the labor market is considered near-full employment. The Fed's dual mandate includes maximizing employment.",
        "desc_zh": "正在積極求職的勞動力佔比。3.5-4% 附近被認為接近充分就業。聯準會的雙重任務包含最大化就業。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "jobless_claims",
        "series_id": "ICSA",
        "name_en": "Initial Jobless Claims",
        "name_zh": "初次申請失業救濟金人數",
        "desc_en": "Weekly count of newly unemployed individuals filing for benefits. The most timely labor market indicator. A 4-week moving average above 300K often signals labor market deterioration. Markets are sensitive to sharp week-to-week moves.",
        "desc_zh": "每週新申請失業救濟金的人數，是最即時的勞動市場指標。四週移動平均超過 30 萬通常代表勞動市場惡化，市場對每週大幅變動極為敏感。",
        "unit": "Number",
        "unit_zh": "人數",
        "frequency": "Weekly",
        "frequency_zh": "每週",
        "category": "employment",
        "importance": "high",
        "format": "thousands",
    },
    {
        "id": "labor_participation",
        "series_id": "CIVPART",
        "name_en": "Labor Force Participation Rate",
        "name_zh": "勞動參與率",
        "desc_en": "Percentage of working-age population that is employed or actively job-seeking. Low participation can mask real unemployment. Post-COVID, the US LFPR has recovered but remains below pre-pandemic highs due to aging demographics.",
        "desc_zh": "工作年齡人口中就業或積極求職的比例。低參與率可能掩蓋真實失業情況。疫情後美國勞動參與率已回升，但因人口老化，仍低於疫前高點。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "medium",
        "format": "percent",
    },
    {
        "id": "u6_unemployment",
        "series_id": "U6RATE",
        "name_en": "U-6 Underemployment Rate",
        "name_zh": "U-6 廣義失業率",
        "desc_en": "Broadest measure of labor underutilization, including part-time workers who want full-time jobs and marginally attached workers. U-6 typically runs 3-5 percentage points above U-3 (headline unemployment). A narrowing U3/U6 gap indicates a tightening labor market.",
        "desc_zh": "最廣義的勞動力未充分利用指標，包含希望全職工作卻只能兼職者及邊緣勞工。U-6 通常比 U-3（標準失業率）高 3-5 個百分點，兩者差距收窄代表勞動市場緊俏。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "medium",
        "format": "percent",
    },

    # ── 成長 ──────────────────────────────────────────────────────────────
    {
        "id": "real_gdp",
        "series_id": "GDPC1",
        "name_en": "Real GDP (Annualized)",
        "name_zh": "實質 GDP（年化）",
        "desc_en": "Inflation-adjusted total output of the US economy. Two consecutive quarters of negative real GDP growth constitutes a technical recession. Healthy growth is generally 2-3% annualized. This is the definitive measure of economic health.",
        "desc_zh": "經通膨調整的美國經濟總產出。連續兩季負成長即為技術性衰退。健康的成長率約為年化 2-3%，是最終極的經濟健康指標。",
        "unit": "Bil. Chained 2017 $",
        "unit_zh": "十億美元（2017年連鎖價）",
        "frequency": "Quarterly",
        "frequency_zh": "每季",
        "category": "growth",
        "importance": "high",
        "format": "billions",
    },
    {
        "id": "retail_sales",
        "series_id": "RSXFS",
        "name_en": "Retail Sales (ex Autos)",
        "name_zh": "零售銷售額（不含汽車）",
        "desc_en": "Monthly measure of consumer spending at retail stores, excluding volatile auto sales. Consumer spending drives ~70% of US GDP, so strong retail sales signal economic resilience. A sharp miss can trigger equity market selloffs.",
        "desc_zh": "每月零售商場消費支出，剔除波動較大的汽車銷售。消費支出佔美國 GDP 約 70%，強勁的零售銷售代表經濟韌性，大幅低於預期可能引發股市賣壓。",
        "unit": "Millions of $",
        "unit_zh": "百萬美元",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "growth",
        "importance": "high",
        "format": "billions",
    },
    {
        "id": "industrial_production",
        "series_id": "INDPRO",
        "name_en": "Industrial Production Index",
        "name_zh": "工業生產指數",
        "desc_en": "Measures output of US factories, mines, and utilities. Industrial production accounts for about 15% of GDP but is more volatile and leads economic turning points. A sustained decline often precedes recession.",
        "desc_zh": "衡量美國工廠、礦業和公用事業的產出。工業生產佔 GDP 約 15%，波動較大但能領先經濟轉折點，持續下滑往往是衰退先兆。",
        "unit": "Index (2017=100)",
        "unit_zh": "指數（2017=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "growth",
        "importance": "medium",
        "format": "index",
    },
    {
        "id": "pce",
        "series_id": "PCE",
        "name_en": "Personal Consumption Expenditures",
        "name_zh": "個人消費支出 PCE",
        "desc_en": "Total spending by US households on goods and services. PCE is broader than retail sales and is the primary component of GDP. A deceleration in PCE growth warns of economic softening even when headline unemployment stays low.",
        "desc_zh": "美國家庭在商品和服務上的總支出，比零售銷售更廣泛，是 GDP 的主要組成部分。PCE 成長放緩是經濟趨軟的警示，即使失業率仍低。",
        "unit": "Billions of $",
        "unit_zh": "十億美元",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "growth",
        "importance": "medium",
        "format": "billions",
    },
    {
        "id": "fed_rate",
        "series_id": "FEDFUNDS",
        "name_en": "Federal Funds Rate",
        "name_zh": "聯邦基金利率",
        "desc_en": "The interest rate at which banks lend reserve balances to each other overnight—the primary policy tool of the Federal Reserve. Rate hikes cool inflation but risk slowing growth; cuts stimulate the economy. Every basis point move ripples across all asset classes.",
        "desc_zh": "銀行間隔夜拆借準備金的利率，是聯準會的主要政策工具。升息可抑制通膨但有壓縮成長的風險；降息可刺激經濟。每一個基點的變動都會波及所有資產類別。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "growth",
        "importance": "high",
        "format": "percent",
    },

    # ── 房市 ──────────────────────────────────────────────────────────────
    {
        "id": "housing_starts",
        "series_id": "HOUST",
        "name_en": "Housing Starts",
        "name_zh": "新屋開工數",
        "desc_en": "Number of new residential construction projects begun per month. Housing is a leading indicator—builders break ground based on demand expectations 6-18 months out. A drop in starts signals a cooling market well before prices adjust.",
        "desc_zh": "每月開始動工的新住宅建設數量。房屋建設是領先指標，建商依據 6-18 個月後的需求預期動工。開工數下降是房市降溫的早期訊號，早於房價反應。",
        "unit": "Thousands of Units",
        "unit_zh": "千戶",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "housing",
        "importance": "medium",
        "format": "thousands",
    },
    {
        "id": "building_permits",
        "series_id": "PERMIT",
        "name_en": "Building Permits",
        "name_zh": "建築許可數",
        "desc_en": "Number of new construction permits issued monthly. Permits are issued before construction starts, making them an even more leading indicator than housing starts—often 1-2 months ahead. A permit trend closely tracks future housing supply.",
        "desc_zh": "每月核發的新建築許可數量。許可在施工前核發，比新屋開工數更具領先性，通常早 1-2 個月反映趨勢，許可趨勢緊密追蹤未來住宅供給。",
        "unit": "Thousands of Units",
        "unit_zh": "千戶",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "housing",
        "importance": "medium",
        "format": "thousands",
    },
    {
        "id": "existing_home_sales",
        "series_id": "EXHOSLUSM495S",
        "name_en": "Existing Home Sales",
        "name_zh": "成屋銷售量",
        "desc_en": "Monthly count of completed sales of previously constructed homes. Existing home sales account for ~85% of total home sales and reflect real-time demand. A decline signals affordability stress, usually from high mortgage rates or prices.",
        "desc_zh": "每月已建成住宅的成交量，佔全美房屋銷售約 85%，反映即時需求。銷量下滑代表購房負擔壓力增大，通常源於高房貸利率或高房價。",
        "unit": "Thousands of Units",
        "unit_zh": "千戶",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "housing",
        "importance": "medium",
        "format": "thousands",
    },
    {
        "id": "mortgage_rate",
        "series_id": "MORTGAGE30US",
        "name_en": "30-Year Mortgage Rate",
        "name_zh": "30年期房貸利率",
        "desc_en": "Average interest rate for a 30-year fixed mortgage in the US. Mortgage rates typically move with the 10-year Treasury yield plus a spread. Above 7% significantly pressures housing affordability and can freeze transaction volume.",
        "desc_zh": "美國 30 年期固定房貸平均利率。房貸利率通常隨 10 年期美債殖利率加上利差波動，超過 7% 會顯著壓縮購房可負擔性並可能凍結成交量。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Weekly",
        "frequency_zh": "每週",
        "category": "housing",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "case_shiller",
        "series_id": "CSUSHPISA",
        "name_en": "Case-Shiller Home Price Index",
        "name_zh": "凱斯-席勒房價指數",
        "desc_en": "The gold standard for tracking US home price changes across 20 major metropolitan areas using a repeat-sales methodology. Published with a 2-month lag. YoY changes above 10% signal speculative excess; consecutive monthly declines signal a correction.",
        "desc_zh": "追蹤 20 個主要大都會區房價變化的黃金標準指標，採用重複銷售方法論。發布有約 2 個月滯後。年增率超過 10% 代表投機過熱，連續月跌代表房市修正。",
        "unit": "Index (Jan 2000=100)",
        "unit_zh": "指數（2000年1月=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "housing",
        "importance": "medium",
        "format": "index",
    },

    # ── 製造業 ────────────────────────────────────────────────────────────
    {
        "id": "mfg_employment",
        "series_id": "MANEMP",
        "name_en": "Manufacturing Employment",
        "name_zh": "製造業就業人數",
        "desc_en": "Total US manufacturing sector employment (BLS payrolls). A leading indicator for the goods-producing economy. Sustained YoY declines have historically preceded broader recessions.",
        "desc_zh": "美國製造業總就業人數（勞工部薪資調查）。商品生產經濟的領先指標，年增率持續為負通常領先整體衰退。",
        "unit": "Thousands of Persons",
        "unit_zh": "千人",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "high",
        "format": "thousands",
    },
    {
        "id": "durable_goods",
        "series_id": "DGORDER",
        "name_en": "Durable Goods Orders",
        "name_zh": "耐久財訂單",
        "desc_en": "Monthly value of new orders placed for manufactured goods expected to last 3+ years (aircraft, machinery, vehicles). Highly volatile due to aircraft orders. The ex-defense, ex-aircraft 'core capital goods' measure is preferred for clean business investment trends.",
        "desc_zh": "每月製造業新接的耐久財訂單（使用 3 年以上如飛機、機械、車輛）。因飛機訂單而波動極大。剔除國防和飛機的「核心資本財」指標更能反映乾淨的商業投資趨勢。",
        "unit": "Millions of $",
        "unit_zh": "百萬美元",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "medium",
        "format": "billions",
    },
    {
        "id": "manufacturing_production",
        "series_id": "IPMAN",
        "name_en": "Industrial Production: Manufacturing",
        "name_zh": "工業生產：製造業",
        "desc_en": "Index measuring the real output of the manufacturing sector (subset of total industrial production). Captures factory floor activity in real time. A sustained decline in manufacturing production often precedes broader economic slowdowns by 2-3 quarters.",
        "desc_zh": "衡量製造業實際產出的指數（工業生產總指數的子集）。即時捕捉工廠生產動態。製造業生產持續下滑，往往比整體經濟放緩早 2-3 季出現。",
        "unit": "Index (2017=100)",
        "unit_zh": "指數（2017=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "medium",
        "format": "index",
    },
    {
        "id": "consumer_sentiment",
        "series_id": "UMCSENT",
        "name_en": "Consumer Sentiment (UMich)",
        "name_zh": "密大消費者信心指數",
        "desc_en": "Monthly University of Michigan survey of consumer confidence about current and future economic conditions. Acts as both a coincident and leading indicator—a sharp drop in sentiment can become self-fulfilling as consumers pull back on spending.",
        "desc_zh": "密西根大學每月調查消費者對當前和未來經濟狀況的信心，兼具同步和領先指標功能。信心大幅下滑可能自我實現，因為消費者會縮減支出。",
        "unit": "Index (1966:Q1=100)",
        "unit_zh": "指數（1966年第一季=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "medium",
        "format": "index",
    },

    # ── 金融市場 ──────────────────────────────────────────────────────────
    {
        "id": "yield_curve_2_10",
        "series_id": "T10Y2Y",
        "name_en": "10Y-2Y Treasury Spread",
        "name_zh": "10年-2年公債利差",
        "desc_en": "The spread between 10-year and 2-year Treasury yields. An inverted curve (negative spread) has preceded every US recession since 1955 by 6-18 months. Re-steepening from inversion is often the most reliable recession imminence signal.",
        "desc_zh": "10年期與2年期美債殖利率差。曲線倒掛（負值）自1955年以來每次都領先美國經濟衰退6-18個月。從倒掛回正陡峭化，是衰退迫近的最可靠訊號之一。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "yield_curve_3m_10y",
        "series_id": "T10Y3M",
        "name_en": "10Y-3M Treasury Spread",
        "name_zh": "10年-3月公債利差",
        "desc_en": "The 10-year minus 3-month Treasury spread—the NY Fed's preferred recession indicator. Inversion has accurately predicted 8 of the last 8 US recessions. Watched more closely by economists than 10Y-2Y.",
        "desc_zh": "10年期減3個月期美債利差，為紐約聯儲偏好的衰退指標。倒掛準確預測過去8次美國衰退中的全部8次，經濟學家比10年-2年利差更看重此指標。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "treasury_10y",
        "series_id": "DGS10",
        "name_en": "10-Year Treasury Yield",
        "name_zh": "10年期美債殖利率",
        "desc_en": "Yield on the benchmark 10-year US Treasury note. Drives mortgage rates, corporate borrowing costs, and is the global risk-free benchmark. Rising 10Y yields pressure equity valuations, especially high-duration tech stocks.",
        "desc_zh": "10年期美國國債的基準殖利率，是房貸、企業借貸成本的指標，也是全球無風險利率基準。10年殖利率上升會壓縮股市估值，尤其衝擊長存續期的科技股。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "treasury_2y",
        "series_id": "DGS2",
        "name_en": "2-Year Treasury Yield",
        "name_zh": "2年期美債殖利率",
        "desc_en": "Yield on 2-year Treasury notes, closely tracking Fed policy expectations. The 2-year reflects what markets expect the Fed Funds rate to average over the next two years. Sharp moves often telegraph FOMC pivots before they happen.",
        "desc_zh": "2年期美債殖利率，緊密追蹤聯準會政策預期。反映市場對未來兩年聯邦基金利率平均水準的預期，大幅波動常領先 FOMC 政策轉向。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "medium",
        "format": "percent",
    },
    {
        "id": "vix",
        "series_id": "VIXCLS",
        "name_en": "VIX Volatility Index",
        "name_zh": "VIX 恐慌指數",
        "desc_en": "CBOE Volatility Index, measuring implied volatility on S&P 500 options. Below 15 = complacency; 20-30 = caution; above 40 = panic. VIX spikes correlate with sharp equity selloffs and flight-to-safety flows.",
        "desc_zh": "芝加哥選擇權交易所波動率指數，衡量標普500選擇權的隱含波動率。低於15代表市場自滿，20-30為警戒，高於40為恐慌。VIX飆升常伴隨股市大跌與避險資金流入。",
        "unit": "Index",
        "unit_zh": "指數",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "high",
        "format": "index",
    },
    {
        "id": "hy_oas",
        "series_id": "BAMLH0A0HYM2",
        "name_en": "High Yield OAS Spread",
        "name_zh": "高收益債利差",
        "desc_en": "ICE BofA US High Yield Index Option-Adjusted Spread—the premium investors demand to hold junk bonds vs. Treasuries. Below 400bps = risk-on; above 600bps = stress; above 1000bps = recession-grade panic. Leading indicator of credit cycle turns.",
        "desc_zh": "ICE BofA 美國高收益債券指數選擇權調整利差，投資人持有垃圾債相對美債所要求的風險溢酬。低於 400bps 為風險偏好，高於 600bps 為壓力，超過 1000bps 為衰退級恐慌。是信用循環轉折的領先指標。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "high",
        "format": "percent",
    },
    {
        "id": "dxy",
        "series_id": "DTWEXBGS",
        "name_en": "Trade-Weighted Dollar Index",
        "name_zh": "貿易加權美元指數",
        "desc_en": "Fed's broad trade-weighted dollar index against major trading partners' currencies. A strong dollar pressures multinational earnings, commodity prices (negatively), and emerging market debt. A weakening dollar typically boosts US equities and EM assets.",
        "desc_zh": "聯準會編製的貿易加權廣義美元指數，對美國主要貿易夥伴貨幣加權。強勢美元壓縮跨國企業獲利、商品價格與新興市場債務；弱勢美元通常利多美股與新興市場資產。",
        "unit": "Index (Jan 2006=100)",
        "unit_zh": "指數（2006年1月=100）",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "medium",
        "format": "index",
    },
    {
        "id": "wti_oil",
        "series_id": "DCOILWTICO",
        "name_en": "WTI Crude Oil Price",
        "name_zh": "WTI 原油價格",
        "desc_en": "West Texas Intermediate crude oil spot price per barrel. Oil prices feed into inflation, transportation costs, and consumer discretionary spending. Sustained moves above $90 typically pressure CPI; below $60 raises concerns about global demand.",
        "desc_zh": "西德州中級原油現貨價格（每桶美元）。油價影響通膨、運輸成本與消費者可支配支出。持續高於 90 美元常推高 CPI；低於 60 美元則引發全球需求疑慮。",
        "unit": "$/Barrel",
        "unit_zh": "美元/桶",
        "frequency": "Daily",
        "frequency_zh": "每日",
        "category": "financial",
        "importance": "medium",
        "format": "index",
    },
    {
        "id": "m2",
        "series_id": "M2SL",
        "name_en": "M2 Money Supply",
        "name_zh": "M2 貨幣供給",
        "desc_en": "Broad measure of US money supply including currency, deposits, and money market funds. M2 YoY growth correlates with inflation 12-18 months ahead. Post-2022 contraction was the first since the Great Depression, signaling tight liquidity.",
        "desc_zh": "美國廣義貨幣供給，含現金、存款與貨幣市場基金。M2 年增率領先通膨 12-18 個月。2022 年後的萎縮是自大蕭條以來首見，反映流動性緊縮。",
        "unit": "Billions of $",
        "unit_zh": "十億美元",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "financial",
        "importance": "medium",
        "format": "billions",
    },
    # ── 就業（補強）──────────────────────────────────────────────────────
    {
        "id": "jolts",
        "series_id": "JTSJOL",
        "name_en": "JOLTS Job Openings",
        "name_zh": "JOLTS 職位空缺",
        "desc_en": "Job Openings and Labor Turnover Survey from BLS—total unfilled job postings. The job openings to unemployed ratio (currently watched closely by Powell) signals labor market tightness. A drop below 1.0 typically precedes wage disinflation.",
        "desc_zh": "勞工部 JOLTS 調查的未填補職位總數。職位空缺對失業人數比率（鮑爾密切關注的指標）反映勞動市場緊俏程度，低於 1.0 通常領先工資通膨降溫。",
        "unit": "Thousands",
        "unit_zh": "千個",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "high",
        "format": "thousands",
    },
    {
        "id": "avg_hourly_earnings",
        "series_id": "CES0500000003",
        "name_en": "Avg Hourly Earnings (Private)",
        "name_zh": "平均時薪（民間部門）",
        "desc_en": "Average hourly earnings of all private-sector employees. YoY growth above 4% is consistent with sticky 2%+ services inflation. Fed watches wage growth as the lynchpin of services inflation dynamics.",
        "desc_zh": "民間部門全體勞工平均時薪。年增率高於 4% 與黏性 2%+ 服務業通膨一致。聯準會將工資成長視為服務業通膨動態的關鍵指標。",
        "unit": "$/Hour",
        "unit_zh": "美元/小時",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "employment",
        "importance": "high",
        "format": "index",
    },
    # ── 製造業（補強）──────────────────────────────────────────────────
    {
        "id": "capacity_utilization",
        "series_id": "TCU",
        "name_en": "Capacity Utilization",
        "name_zh": "工業產能利用率",
        "desc_en": "Percentage of industrial capacity actually in use. Above 80% indicates tight capacity (inflationary pressure); below 75% signals slack (deflationary). Recession averages historically run 73-75%.",
        "desc_zh": "工業產能實際使用比例。高於 80% 代表產能吃緊（通膨壓力），低於 75% 代表閒置（通縮壓力）。歷史衰退期平均落在 73-75%。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "medium",
        "format": "percent",
    },
    {
        "id": "leading_index",
        "series_id": "USSLIND",
        "name_en": "Leading Economic Index (Phila Fed)",
        "name_zh": "費城聯儲領先經濟指數",
        "desc_en": "Philadelphia Fed's State Leading Index based on housing permits, jobless claims, manufacturing hours, and yield spread. Six consecutive negative months has historically signaled recession with 80%+ accuracy.",
        "desc_zh": "費城聯儲編製，綜合建築許可、初領失業金、製造業工時與利差等領先指標。連續六個月為負歷史上以 80%+ 準確率預測衰退。",
        "unit": "%",
        "unit_zh": "%",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "manufacturing",
        "importance": "medium",
        "format": "percent",
    },
    # ── 貿易 ──────────────────────────────────────────────────────────────
    {
        "id": "trade_balance",
        "series_id": "BOPGSTB",
        "name_en": "Trade Balance (Goods & Services)",
        "name_zh": "貿易餘額（商品與服務）",
        "desc_en": "Difference between US exports and imports of goods/services. Persistent deficits (currently ~$70B/month) pressure the dollar long-term. Sudden widening can signal domestic demand strength or import surges (often China-related).",
        "desc_zh": "美國商品與服務出口減進口的差額。持續赤字（目前約每月 700 億美元）長期施壓美元。突然擴大可能反映內需強勁或進口激增（常與中國貿易相關）。",
        "unit": "Millions of $",
        "unit_zh": "百萬美元",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "trade",
        "importance": "medium",
        "format": "billions",
    },
    {
        "id": "import_prices",
        "series_id": "IR",
        "name_en": "Import Price Index (Overall)",
        "name_zh": "進口物價指數（綜合）",
        "desc_en": "BLS import price index covering all imported goods. A leading indicator for goods CPI—rising import prices typically pass through to consumer inflation within 1-3 quarters. Closely watched during trade-tension episodes.",
        "desc_zh": "勞工部編製的全進口商品價格指數，是商品 CPI 的領先指標。進口物價上升通常 1-3 季後轉嫁至消費通膨，在貿易摩擦時期備受關注。",
        "unit": "Index (2000=100)",
        "unit_zh": "指數（2000=100）",
        "frequency": "Monthly",
        "frequency_zh": "每月",
        "category": "trade",
        "importance": "medium",
        "format": "index",
    },
]

INDICATOR_MAP = {ind["series_id"]: ind for ind in INDICATORS}
INDICATOR_BY_ID = {ind["id"]: ind for ind in INDICATORS}
